-- MySQL Script generated by MySQL Workbench
-- Sun Apr 23 14:23:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sprint_telovendo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sprint_telovendo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sprint_telovendo` DEFAULT CHARACTER SET utf8 ;
USE `sprint_telovendo` ;

-- -----------------------------------------------------
-- Table `sprint_telovendo`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint_telovendo`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nom_representante` VARCHAR(45) NULL,
  `nom_corporativo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `nom_contacto` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `cat_prod` VARCHAR(45) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sprint_telovendo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint_telovendo`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sprint_telovendo`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sprint_telovendo`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nom_prod` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `cat_prod` VARCHAR(45) NULL,
  `proveedor` VARCHAR(45) NULL,
  `stock` INT NULL,
  `color` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `sprint_telovendo`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `sprint_telovendo`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
